// Workout exercises for women's safety training — full 44-exercise dataset

// ── Legacy types (kept for backward compat) ──────────────────────────────────

export type WorkoutCategory =
  | 'SELF_DEFENSE'
  | 'AGILITY_REACTION'
  | 'STRENGTH_POWER'
  | 'ENDURANCE_ESCAPE';

export type ExerciseSection = 'warm-up' | 'strength' | 'cardio' | 'cool-down' | 'flexibility';

// ── New tab type ──────────────────────────────────────────────────────────────

export type TabCategory = 'strength' | 'self-defence' | 'cardio' | 'flexibility' | 'core';

// ── Exercise type ─────────────────────────────────────────────────────────────

export type WorkoutExercise = {
  exercise_id: string;
  title: string;
  description: string;
  instructions: string[];
  animation_url?: string;
  duration_seconds: number;
  section: ExerciseSection;
  category: WorkoutCategory;
  reps_or_duration: string;
  difficulty_level: 'beginner' | 'intermediate' | 'advanced';
  safety_focus: string;
  muscle_groups: string[];
  video_urls?: { male?: string[]; female?: string[] };
  // new required fields
  tab: TabCategory;
  sets: number;
  reps_display: string;
  rest_seconds: number;
  is_timed: boolean;
  set_duration_seconds?: number;
};

// ── Module-level completion tracking (cross-screen) ───────────────────────────

export const sessionCompleted = new Set<string>();

// ── Category config (legacy, kept for compat) ────────────────────────────────

export const WORKOUT_CATEGORY_CONFIG = {
  SELF_DEFENSE: {
    name: 'Self-Defense Fitness',
    description: 'Build strength and agility for personal protection',
    color: '#FF6B6B',
    focus: 'Core stability, balance, and functional strength for self-defense situations',
  },
  AGILITY_REACTION: {
    name: 'Agility & Reaction',
    description: 'Quick movement and situational awareness training',
    color: '#4ECDC4',
    focus: 'Footwork, reaction time, and spatial awareness for threat evasion',
  },
  STRENGTH_POWER: {
    name: 'Strength & Power',
    description: 'Build functional strength for everyday safety',
    color: '#FFD93D',
    focus: 'Upper body strength, grip strength, and explosive power',
  },
  ENDURANCE_ESCAPE: {
    name: 'Endurance & Escape',
    description: 'Cardiovascular fitness for emergency situations',
    color: '#95E1D3',
    focus: 'Stamina, running endurance, and sustained energy for escape scenarios',
  },
};

// ── Helper: compute duration_seconds ─────────────────────────────────────────
// sets * (is_timed ? set_duration_seconds : 30) + (sets - 1) * rest_seconds

function calcDuration(sets: number, isTimed: boolean, setDur: number, rest: number): number {
  return sets * (isTimed ? setDur : 30) + (sets - 1) * rest;
}

// ── All 44 exercises ──────────────────────────────────────────────────────────

export const ALL_EXERCISES: WorkoutExercise[] = [

  // ── STRENGTH TAB ────────────────────────────────────────────────────────────

  {
    exercise_id: 'str_squat',
    title: 'Barbell Back Squat',
    description: 'A compound lower body exercise using a barbell across your upper back. It builds quad, glute, and hamstring strength and is the foundation of lower-body training.',
    instructions: [
      'Set the barbell on a squat rack at shoulder height, step under it, and rest it across your upper traps.',
      'Grip the bar slightly wider than shoulder-width, unrack it, and step back with feet shoulder-width apart, toes slightly out.',
      'Take a deep breath, brace your core, and begin descending by pushing your hips back and bending your knees.',
      'Lower until your thighs are parallel to the floor (or slightly below), keeping chest up and knees tracking over toes.',
      'Drive through your heels to stand back up, exhaling at the top.',
      'Complete all reps, then step forward to re-rack the bar safely.',
    ],
    duration_seconds: calcDuration(4, false, 30, 90),
    section: 'strength',
    category: 'STRENGTH_POWER',
    reps_or_duration: '8-10 reps',
    difficulty_level: 'intermediate',
    safety_focus: 'Lower body strength and stability',
    muscle_groups: ['quadriceps', 'glutes', 'hamstrings', 'core'],
    tab: 'strength',
    sets: 4,
    reps_display: '8-10 reps',
    rest_seconds: 90,
    is_timed: false,
  },

  {
    exercise_id: 'str_deadlift',
    title: 'Deadlift',
    description: 'A fundamental compound lift that targets the entire posterior chain. Builds raw strength in the hamstrings, glutes, and lower back.',
    instructions: [
      'Stand with feet hip-width apart, barbell over your mid-foot. Grip the bar just outside your legs.',
      'Hinge at the hips and bend your knees until your shins touch the bar. Keep your back flat and chest tall.',
      'Take a deep breath, brace your core hard, and push the floor away as you drive your hips forward.',
      'Keep the bar close to your body as it rises — drag it up your shins and thighs.',
      'Stand fully upright at the top, squeezing your glutes, without hyperextending your lower back.',
      'Lower the bar back to the floor in a controlled manner by hinging at the hips first, then bending the knees.',
    ],
    duration_seconds: calcDuration(4, false, 30, 120),
    section: 'strength',
    category: 'STRENGTH_POWER',
    reps_or_duration: '6-8 reps',
    difficulty_level: 'advanced',
    safety_focus: 'Posterior chain power',
    muscle_groups: ['hamstrings', 'glutes', 'lower back', 'core'],
    tab: 'strength',
    sets: 4,
    reps_display: '6-8 reps',
    rest_seconds: 120,
    is_timed: false,
  },

  {
    exercise_id: 'str_bench',
    title: 'Bench Press',
    description: 'The classic upper body pushing exercise. Targets the chest, shoulders, and triceps to build pushing strength.',
    instructions: [
      'Lie flat on a bench with your feet planted on the floor. Grip the barbell slightly wider than shoulder-width.',
      'Unrack the bar and hold it directly over your chest with arms fully extended.',
      'Lower the bar slowly to your chest, keeping elbows at a 45–75 degree angle from your torso.',
      'Touch the bar lightly to your chest — do not bounce it.',
      'Press the bar back up explosively to the starting position, exhaling at the top.',
      'After all reps, carefully rack the bar with control.',
    ],
    duration_seconds: calcDuration(4, false, 30, 90),
    section: 'strength',
    category: 'STRENGTH_POWER',
    reps_or_duration: '8-10 reps',
    difficulty_level: 'intermediate',
    safety_focus: 'Upper body pushing strength',
    muscle_groups: ['chest', 'shoulders', 'triceps'],
    tab: 'strength',
    sets: 4,
    reps_display: '8-10 reps',
    rest_seconds: 90,
    is_timed: false,
  },

  {
    exercise_id: 'str_ohp',
    title: 'Overhead Press',
    description: 'A standing shoulder press that builds overhead strength and shoulder stability. Core must stay braced throughout.',
    instructions: [
      'Stand with feet shoulder-width apart. Hold a barbell or dumbbells at shoulder height, palms facing forward.',
      'Brace your core and squeeze your glutes to protect your lower back.',
      'Press the weight straight up overhead until arms are fully extended.',
      'Keep the bar over your centre of gravity — slightly behind your head at the top.',
      'Lower back to shoulder height in a controlled manner.',
      'Repeat for all reps, keeping the movement smooth and controlled.',
    ],
    duration_seconds: calcDuration(3, false, 30, 60),
    section: 'strength',
    category: 'STRENGTH_POWER',
    reps_or_duration: '10-12 reps',
    difficulty_level: 'intermediate',
    safety_focus: 'Shoulder strength and stability',
    muscle_groups: ['shoulders', 'triceps', 'upper back'],
    tab: 'strength',
    sets: 3,
    reps_display: '10-12 reps',
    rest_seconds: 60,
    is_timed: false,
  },

  {
    exercise_id: 'str_row',
    title: 'Bent Over Row',
    description: 'A barbell or dumbbell row performed in a hinged position. Excellent for building upper back thickness and improving posture.',
    instructions: [
      'Stand with feet hip-width apart. Hinge forward at the hips until your torso is roughly parallel to the floor.',
      'Hold the barbell or dumbbells with an overhand grip, arms hanging directly below your shoulders.',
      'Keep your back flat and core braced — do not round your lower back.',
      'Row the weight up toward your lower chest/upper abdomen, driving your elbows back.',
      'Squeeze your shoulder blades together at the top of the movement.',
      'Lower the weight slowly back to the starting position and repeat.',
    ],
    duration_seconds: calcDuration(4, false, 30, 90),
    section: 'strength',
    category: 'STRENGTH_POWER',
    reps_or_duration: '8-10 reps',
    difficulty_level: 'intermediate',
    safety_focus: 'Back strength and posture',
    muscle_groups: ['upper back', 'biceps', 'core'],
    tab: 'strength',
    sets: 4,
    reps_display: '8-10 reps',
    rest_seconds: 90,
    is_timed: false,
  },

  {
    exercise_id: 'str_pullup',
    title: 'Pull Ups',
    description: 'A bodyweight exercise that builds upper back and bicep strength. One of the best indicators of relative upper body strength.',
    instructions: [
      'Hang from a pull-up bar with an overhand grip, hands slightly wider than shoulder-width.',
      'Let your arms fully extend and engage your core so you are not swinging.',
      'Pull your chest toward the bar by driving your elbows down and back.',
      'Continue pulling until your chin clears the bar.',
      'Pause briefly at the top, then lower yourself in a controlled 2-3 second count.',
      'Fully extend your arms at the bottom before starting the next rep.',
    ],
    duration_seconds: calcDuration(3, false, 30, 90),
    section: 'strength',
    category: 'STRENGTH_POWER',
    reps_or_duration: '6-10 reps',
    difficulty_level: 'advanced',
    safety_focus: 'Upper body pulling strength',
    muscle_groups: ['upper back', 'biceps', 'core'],
    tab: 'strength',
    sets: 3,
    reps_display: '6-10 reps',
    rest_seconds: 90,
    is_timed: false,
  },

  {
    exercise_id: 'str_lunge',
    title: 'Dumbbell Lunges',
    description: 'A unilateral leg exercise that trains each leg independently, improving balance and correcting strength imbalances.',
    instructions: [
      'Stand upright holding a dumbbell in each hand at your sides.',
      'Step forward with your right foot, landing with a soft knee.',
      'Lower your back knee toward the floor until both knees are at roughly 90 degrees.',
      'Keep your torso upright and core braced — do not lean forward excessively.',
      'Push through your front heel to return to standing, then repeat on the left leg.',
      'Alternate legs for the prescribed number of reps on each side.',
    ],
    duration_seconds: calcDuration(3, false, 30, 60),
    section: 'strength',
    category: 'STRENGTH_POWER',
    reps_or_duration: '12 each leg',
    difficulty_level: 'beginner',
    safety_focus: 'Unilateral leg strength',
    muscle_groups: ['quadriceps', 'glutes', 'hamstrings'],
    tab: 'strength',
    sets: 3,
    reps_display: '12 each leg',
    rest_seconds: 60,
    is_timed: false,
  },

  {
    exercise_id: 'str_plank_hold',
    title: 'Plank Hold',
    description: 'An isometric core exercise that builds stability throughout the entire core, shoulders, and glutes.',
    instructions: [
      'Start in a push-up position with your forearms on the floor, elbows directly under your shoulders.',
      'Keep your body in a straight line from head to heels — do not let your hips sag or pike up.',
      'Brace your core as if bracing for a punch, and squeeze your glutes.',
      'Keep your neck neutral — look at the floor just in front of your hands.',
      'Breathe steadily throughout the hold — do not hold your breath.',
      'Hold for the full 45 seconds, then release and rest.',
    ],
    duration_seconds: calcDuration(3, true, 45, 45),
    section: 'strength',
    category: 'STRENGTH_POWER',
    reps_or_duration: '45 sec hold',
    difficulty_level: 'beginner',
    safety_focus: 'Core stability',
    muscle_groups: ['core', 'shoulders', 'glutes'],
    tab: 'strength',
    sets: 3,
    reps_display: '45 sec hold',
    rest_seconds: 45,
    is_timed: true,
    set_duration_seconds: 45,
  },

  {
    exercise_id: 'str_curl',
    title: 'Dumbbell Bicep Curl',
    description: 'A classic isolation exercise for the biceps. Builds arm strength and is easy to learn for beginners.',
    instructions: [
      'Stand with feet shoulder-width apart, holding a dumbbell in each hand with palms facing forward.',
      'Keep your elbows close to your torso and do not swing your body.',
      'Curl the weights up toward your shoulders by flexing your biceps.',
      'Squeeze your biceps hard at the top of the movement.',
      'Lower the dumbbells back down in a slow, controlled manner (2-3 seconds).',
      'Repeat for all reps, keeping the movement strict and controlled.',
    ],
    duration_seconds: calcDuration(3, false, 30, 45),
    section: 'strength',
    category: 'STRENGTH_POWER',
    reps_or_duration: '12-15 reps',
    difficulty_level: 'beginner',
    safety_focus: 'Arm strength',
    muscle_groups: ['biceps', 'forearms'],
    tab: 'strength',
    sets: 3,
    reps_display: '12-15 reps',
    rest_seconds: 45,
    is_timed: false,
  },

  {
    exercise_id: 'str_dips',
    title: 'Tricep Dips',
    description: 'A bodyweight exercise targeting the triceps and chest. Can be performed on parallel bars or a sturdy bench.',
    instructions: [
      'Sit on the edge of a bench or chair with your hands gripping the edge, fingers pointing forward.',
      'Slide your hips off the edge so your weight is supported by your arms, legs extended or slightly bent.',
      'Lower your body by bending your elbows — keep them pointing straight back, not flaring out.',
      'Lower until your upper arms are roughly parallel to the floor (about 90 degree elbow bend).',
      'Push yourself back up to the starting position by straightening your arms.',
      'Repeat for all reps, maintaining control throughout.',
    ],
    duration_seconds: calcDuration(3, false, 30, 45),
    section: 'strength',
    category: 'STRENGTH_POWER',
    reps_or_duration: '10-12 reps',
    difficulty_level: 'beginner',
    safety_focus: 'Tricep and shoulder strength',
    muscle_groups: ['triceps', 'chest', 'shoulders'],
    tab: 'strength',
    sets: 3,
    reps_display: '10-12 reps',
    rest_seconds: 45,
    is_timed: false,
  },

  // ── SELF DEFENCE TAB ─────────────────────────────────────────────────────────

  {
    exercise_id: 'sd_jab',
    title: 'Jab-Cross Punch Combo',
    description: 'The most fundamental striking combination in boxing and self-defence. Builds coordination, striking power, and awareness of range.',
    instructions: [
      'Stand with your non-dominant foot forward, feet shoulder-width apart, and hands up by your chin.',
      'Throw a quick jab with your lead hand — extend your arm fully, rotate your fist, then snap it back.',
      'Immediately follow with a cross from your rear hand — rotate your hips and shoulder to generate power.',
      'Keep your non-punching hand protecting your chin at all times.',
      'Return to your guard position quickly after each combo.',
      'Practice 20 combos at a steady controlled pace before increasing speed.',
    ],
    duration_seconds: calcDuration(4, false, 30, 60),
    section: 'strength',
    category: 'SELF_DEFENSE',
    reps_or_duration: '20 combos',
    difficulty_level: 'beginner',
    safety_focus: 'Striking power and coordination',
    muscle_groups: ['shoulders', 'chest', 'core', 'legs'],
    tab: 'self-defence',
    sets: 4,
    reps_display: '20 combos',
    rest_seconds: 60,
    is_timed: false,
  },

  {
    exercise_id: 'sd_frontkick',
    title: 'Front Kick Practice',
    description: 'A fundamental kick used to create distance from an attacker. Targets the core and hip flexors while building kicking power.',
    instructions: [
      'Stand in a fighting stance with your non-dominant foot forward.',
      'Lift your rear knee up toward your chest in a chambering motion.',
      'Extend your foot forward, striking with the ball of your foot toward a target at hip to stomach height.',
      'Snap the kick out and retract it quickly back to the chambered position.',
      'Return your foot to the floor in a controlled manner.',
      'Perform all reps on one leg, then switch to the other side.',
    ],
    duration_seconds: calcDuration(3, false, 30, 60),
    section: 'strength',
    category: 'SELF_DEFENSE',
    reps_or_duration: '15 each leg',
    difficulty_level: 'beginner',
    safety_focus: 'Distance management and kick power',
    muscle_groups: ['hips', 'quadriceps', 'core'],
    tab: 'self-defence',
    sets: 3,
    reps_display: '15 each leg',
    rest_seconds: 60,
    is_timed: false,
  },

  {
    exercise_id: 'sd_roundhouse',
    title: 'Roundhouse Kick',
    description: 'A powerful rotational kick targeting the side of the body or head. Requires hip flexibility and good balance.',
    instructions: [
      'Stand in a fighting stance and shift your weight onto your lead (front) foot.',
      'Pivot on your supporting foot, turning it outward as you raise your rear knee.',
      'Rotate your hips forward explosively and swing your leg in a circular arc.',
      'Strike with the instep or shin, snapping through the target at knee to mid-torso height.',
      'Retract the leg quickly after the strike to recover your balance.',
      'Plant your foot back down and return to stance before the next rep.',
    ],
    duration_seconds: calcDuration(3, false, 30, 90),
    section: 'strength',
    category: 'SELF_DEFENSE',
    reps_or_duration: '12 each leg',
    difficulty_level: 'intermediate',
    safety_focus: 'Rotational striking power',
    muscle_groups: ['hips', 'glutes', 'hamstrings', 'core'],
    tab: 'self-defence',
    sets: 3,
    reps_display: '12 each leg',
    rest_seconds: 90,
    is_timed: false,
  },

  {
    exercise_id: 'sd_block',
    title: 'Defensive Block Drill',
    description: 'Practice the basic blocking techniques to deflect incoming strikes. Builds forearm strength and defensive reflexes.',
    instructions: [
      'Stand in a guard position with both hands raised to protect your head and chin.',
      'Practice a high block: raise your forearm diagonally above your head to deflect downward strikes.',
      'Practice a cross block: bring one arm across your body to protect your face from a straight punch.',
      'Practice a low block: drop one arm downward to deflect kicks or low strikes.',
      'Alternate between all three block types at a steady rhythm to build muscle memory.',
      'Aim to move each block explosively from your guard position and return quickly.',
    ],
    duration_seconds: calcDuration(4, false, 30, 45),
    section: 'strength',
    category: 'SELF_DEFENSE',
    reps_or_duration: '20 reps',
    difficulty_level: 'beginner',
    safety_focus: 'Blocking incoming strikes',
    muscle_groups: ['forearms', 'shoulders', 'core'],
    tab: 'self-defence',
    sets: 4,
    reps_display: '20 reps',
    rest_seconds: 45,
    is_timed: false,
  },

  {
    exercise_id: 'sd_elbow',
    title: 'Elbow Strike Drill',
    description: 'Short-range striking technique using the elbow. Highly effective in close-quarters situations where punching is not practical.',
    instructions: [
      'Stand in a fighting stance with your guard up.',
      'Raise one arm to shoulder height with elbow bent at 90 degrees.',
      'Drive your elbow horizontally across in a fast, short arc — as if hitting a target directly to your side.',
      'Rotate your torso slightly to add power from your core.',
      'Retract the arm back to guard position immediately after the strike.',
      'Perform all reps on one arm, then switch to the other side.',
    ],
    duration_seconds: calcDuration(3, false, 30, 60),
    section: 'strength',
    category: 'SELF_DEFENSE',
    reps_or_duration: '15 each arm',
    difficulty_level: 'beginner',
    safety_focus: 'Close-range striking',
    muscle_groups: ['triceps', 'shoulders', 'core'],
    tab: 'self-defence',
    sets: 3,
    reps_display: '15 each arm',
    rest_seconds: 60,
    is_timed: false,
  },

  {
    exercise_id: 'sd_knee',
    title: 'Knee Strike Practice',
    description: 'A close-range strike using the knee to target an attacker\'s midsection. Very effective in a clinch or grabbed situation.',
    instructions: [
      'Stand upright and imagine grabbing an attacker by the shoulders or head.',
      'Raise your knee powerfully upward and forward toward a target at hip height.',
      'Lean slightly forward as you drive your knee up to maximise force.',
      'Strike with the top of the knee cap, snapping through the imaginary target.',
      'Return your foot to the floor in a controlled manner and resume your stance.',
      'Perform all reps on one leg before switching to the other side.',
    ],
    duration_seconds: calcDuration(3, false, 30, 60),
    section: 'strength',
    category: 'SELF_DEFENSE',
    reps_or_duration: '15 each leg',
    difficulty_level: 'beginner',
    safety_focus: 'Close-range lower body strike',
    muscle_groups: ['hips', 'core', 'quadriceps'],
    tab: 'self-defence',
    sets: 3,
    reps_display: '15 each leg',
    rest_seconds: 60,
    is_timed: false,
  },

  {
    exercise_id: 'sd_wrist',
    title: 'Wrist Escape Drill',
    description: 'Technique to break free from a wrist grab. Uses the principle of rotating against the thumb — the weakest point of any grip.',
    instructions: [
      'Have a training partner (or practice alone with your other hand) grip one of your wrists firmly.',
      'Keep your grabbed hand relaxed initially — do not pull back, which tightens the grip.',
      'Rotate your wrist so your thumb side points toward the attacker\'s thumb.',
      'In one sharp motion, pull your arm back and downward toward the gap in their grip (toward the thumb).',
      'As you pull free, step backward to create distance.',
      'Perform all reps on one side, then switch wrists.',
    ],
    duration_seconds: calcDuration(3, false, 30, 45),
    section: 'strength',
    category: 'SELF_DEFENSE',
    reps_or_duration: '10 each side',
    difficulty_level: 'beginner',
    safety_focus: 'Escaping wrist grabs',
    muscle_groups: ['forearms', 'wrists', 'shoulders'],
    tab: 'self-defence',
    sets: 3,
    reps_display: '10 each side',
    rest_seconds: 45,
    is_timed: false,
  },

  {
    exercise_id: 'sd_bearhug',
    title: 'Bear Hug Escape',
    description: 'Technique to escape when grabbed from behind in a bear hug (arms pinned or free). Uses dropping weight and striking to break free.',
    instructions: [
      'Start standing. Imagine an attacker has grabbed you from behind, pinning your arms.',
      'Immediately drop your weight by bending your knees — this lowers your centre of gravity and makes it harder to lift you.',
      'Stomp down firmly on the attacker\'s foot with your heel to cause pain and loosen the grip.',
      'Once the grip loosens, thrust your head backward sharply to strike their face.',
      'Drop one shoulder and spin rapidly to break out of the hold.',
      'Step away quickly and move to create distance. Practice the sequence at slow speed first.',
    ],
    duration_seconds: calcDuration(3, false, 30, 60),
    section: 'strength',
    category: 'SELF_DEFENSE',
    reps_or_duration: '10 reps',
    difficulty_level: 'intermediate',
    safety_focus: 'Escaping hold attacks',
    muscle_groups: ['core', 'legs', 'shoulders'],
    tab: 'self-defence',
    sets: 3,
    reps_display: '10 reps',
    rest_seconds: 60,
    is_timed: false,
  },

  {
    exercise_id: 'sd_hammer',
    title: 'Hammer Fist Strike',
    description: 'A downward or sideways strike using the bottom of the fist. Very powerful and less likely to injure your hand than a regular punch.',
    instructions: [
      'Stand in a fighting stance with one arm raised above shoulder height, fist clenched.',
      'Drive your fist downward in a hammer-like motion, striking with the padded bottom of your fist.',
      'Rotate your torso to generate power from your core rather than just your arm.',
      'Aim for a target at shoulder to head height — the back of the neck, collarbone, or nose.',
      'Retract your arm back to guard position immediately after each strike.',
      'Perform all reps on one arm, then switch sides.',
    ],
    duration_seconds: calcDuration(3, false, 30, 45),
    section: 'strength',
    category: 'SELF_DEFENSE',
    reps_or_duration: '15 each arm',
    difficulty_level: 'beginner',
    safety_focus: 'Downward striking power',
    muscle_groups: ['shoulders', 'forearms', 'core'],
    tab: 'self-defence',
    sets: 3,
    reps_display: '15 each arm',
    rest_seconds: 45,
    is_timed: false,
  },

  {
    exercise_id: 'sd_fall',
    title: 'Fall and Roll Safety',
    description: 'Learn to fall safely without injuring yourself. A critical skill if you are pushed, trip, or are taken to the ground.',
    instructions: [
      'Start by practicing a standing side fall: from a standing position, squat low before falling.',
      'As you fall sideways, slap the mat hard with your arm extended at 45 degrees to disperse the impact.',
      'Tuck your chin to your chest so your head does not strike the ground.',
      'Practice rolling forward: crouch, tuck your chin, and roll over one shoulder diagonally across your back.',
      'Come up onto your feet at the end of the roll, ready to stand and run.',
      'Repeat the fall and roll sequence, alternating directions for each rep.',
    ],
    duration_seconds: calcDuration(3, false, 30, 90),
    section: 'strength',
    category: 'SELF_DEFENSE',
    reps_or_duration: '8 reps',
    difficulty_level: 'intermediate',
    safety_focus: 'Safe falling technique',
    muscle_groups: ['core', 'back', 'legs'],
    tab: 'self-defence',
    sets: 3,
    reps_display: '8 reps',
    rest_seconds: 90,
    is_timed: false,
  },

  // ── CARDIO TAB ───────────────────────────────────────────────────────────────

  {
    exercise_id: 'car_jumprope',
    title: 'Jump Rope',
    description: 'A classic cardio exercise that improves coordination, footwork, and cardiovascular endurance. Great for warming up or steady state cardio.',
    instructions: [
      'Stand with feet together, holding one handle of the jump rope in each hand.',
      'Begin swinging the rope over your head and jump over it as it reaches your feet.',
      'Land softly on the balls of your feet — do not flat-foot each landing.',
      'Keep your elbows close to your sides and use your wrists to swing the rope, not your whole arms.',
      'Maintain a steady rhythm and breathe through your nose if possible.',
      'Continue for the full 2 minutes, slowing to a march in place if you trip.',
    ],
    duration_seconds: calcDuration(4, true, 120, 60),
    section: 'cardio',
    category: 'ENDURANCE_ESCAPE',
    reps_or_duration: '2 min',
    difficulty_level: 'beginner',
    safety_focus: 'Cardio endurance and coordination',
    muscle_groups: ['calves', 'shoulders', 'core'],
    tab: 'cardio',
    sets: 4,
    reps_display: '2 min',
    rest_seconds: 60,
    is_timed: true,
    set_duration_seconds: 120,
  },

  {
    exercise_id: 'car_highknees',
    title: 'High Knees',
    description: 'A running-in-place drill that elevates heart rate quickly and improves hip flexor strength and running mechanics.',
    instructions: [
      'Stand with feet hip-width apart.',
      'Begin jogging in place, lifting your knees as high as possible — ideally to hip height.',
      'Pump your arms in opposition to your legs for balance and momentum.',
      'Land on the balls of your feet and drive off immediately for the next rep.',
      'Keep a fast pace and focus on height, not just speed.',
      'Breathe steadily throughout — aim for a fast but controlled tempo.',
    ],
    duration_seconds: calcDuration(3, true, 45, 30),
    section: 'cardio',
    category: 'ENDURANCE_ESCAPE',
    reps_or_duration: '45 sec',
    difficulty_level: 'beginner',
    safety_focus: 'Running speed and agility',
    muscle_groups: ['hip flexors', 'quadriceps', 'core'],
    tab: 'cardio',
    sets: 3,
    reps_display: '45 sec',
    rest_seconds: 30,
    is_timed: true,
    set_duration_seconds: 45,
  },

  {
    exercise_id: 'car_burpees',
    title: 'Burpees',
    description: 'A full-body conditioning exercise that builds explosive power and cardiovascular fitness. One of the most efficient exercises you can do.',
    instructions: [
      'Stand with feet shoulder-width apart.',
      'Drop your hands to the floor in front of you, just outside your feet.',
      'Jump your feet back into a push-up position. Your body should be in a straight line.',
      'Perform one push-up (optional but recommended for full burpees).',
      'Jump your feet back toward your hands, landing in a low squat.',
      'Explode upward, jumping as high as you can with arms overhead. Land softly and immediately begin the next rep.',
    ],
    duration_seconds: calcDuration(4, false, 30, 90),
    section: 'cardio',
    category: 'ENDURANCE_ESCAPE',
    reps_or_duration: '10 reps',
    difficulty_level: 'intermediate',
    safety_focus: 'Full body explosive power',
    muscle_groups: ['full body', 'chest', 'legs', 'core'],
    tab: 'cardio',
    sets: 4,
    reps_display: '10 reps',
    rest_seconds: 90,
    is_timed: false,
  },

  {
    exercise_id: 'car_boxjump',
    title: 'Box Jumps',
    description: 'A plyometric exercise that develops explosive leg power and fast-twitch muscle recruitment. Great for developing the ability to move suddenly.',
    instructions: [
      'Stand in front of a sturdy box or platform (start with 12–20 inches height).',
      'Bend your knees and swing your arms back to prepare for the jump.',
      'Explode upward and forward, swinging arms forward for momentum.',
      'Land softly on the box with both feet, absorbing the impact by bending your knees.',
      'Stand fully upright on the box, then step or jump back down — do not jump down at high fatigue.',
      'Reset your position and immediately go into the next rep.',
    ],
    duration_seconds: calcDuration(3, false, 30, 60),
    section: 'cardio',
    category: 'ENDURANCE_ESCAPE',
    reps_or_duration: '12 reps',
    difficulty_level: 'intermediate',
    safety_focus: 'Explosive leg power',
    muscle_groups: ['quadriceps', 'glutes', 'calves'],
    tab: 'cardio',
    sets: 3,
    reps_display: '12 reps',
    rest_seconds: 60,
    is_timed: false,
  },

  {
    exercise_id: 'car_mountain',
    title: 'Mountain Climbers',
    description: 'A dynamic core exercise that also elevates heart rate. Simulates a climbing motion while in the push-up position.',
    instructions: [
      'Start in a high push-up (plank) position — hands directly under your shoulders, body in a straight line.',
      'Brace your core hard throughout the entire movement.',
      'Drive your right knee forward toward your chest as far as possible.',
      'Quickly switch — extend your right leg back while simultaneously driving your left knee forward.',
      'Alternate legs rapidly as if running horizontally against the floor.',
      'Keep your hips level — do not let them rise or sag throughout.',
    ],
    duration_seconds: calcDuration(3, false, 30, 45),
    section: 'cardio',
    category: 'ENDURANCE_ESCAPE',
    reps_or_duration: '40 reps',
    difficulty_level: 'beginner',
    safety_focus: 'Core stability and cardio',
    muscle_groups: ['core', 'shoulders', 'hip flexors'],
    tab: 'cardio',
    sets: 3,
    reps_display: '40 reps',
    rest_seconds: 45,
    is_timed: false,
  },

  {
    exercise_id: 'car_sprint',
    title: 'Sprint Intervals',
    description: 'Short all-out sprints followed by rest. Builds maximum speed, power, and the ability to run away from a threat quickly.',
    instructions: [
      'Find an open space of at least 20-30 metres, or use a treadmill.',
      'Start at a slow jog for 5 seconds to build momentum.',
      'At a signal (or timer), accelerate to your absolute maximum speed.',
      'Pump your arms vigorously and drive your knees high — lean slightly forward.',
      'Maintain maximum effort for the full 30 seconds.',
      'At the end of the interval, slow to a walk and allow your heart rate to lower before the next sprint.',
    ],
    duration_seconds: calcDuration(6, true, 30, 90),
    section: 'cardio',
    category: 'ENDURANCE_ESCAPE',
    reps_or_duration: '30 sec sprint',
    difficulty_level: 'advanced',
    safety_focus: 'Maximum speed and escape ability',
    muscle_groups: ['legs', 'core', 'cardiovascular'],
    tab: 'cardio',
    sets: 6,
    reps_display: '30 sec sprint',
    rest_seconds: 90,
    is_timed: true,
    set_duration_seconds: 30,
  },

  {
    exercise_id: 'car_jjack',
    title: 'Jumping Jacks',
    description: 'A simple but effective full-body warm-up and cardio exercise. Great for beginners and as an active recovery drill.',
    instructions: [
      'Stand upright with your feet together and arms at your sides.',
      'In one movement, jump your feet out to slightly wider than shoulder-width while simultaneously raising both arms overhead.',
      'Land softly with your feet wide, arms fully overhead.',
      'Jump again, returning your feet together while lowering your arms back to your sides.',
      'Maintain a steady, controlled rhythm — do not rush.',
      'Keep your core slightly braced and land softly on the balls of your feet each time.',
    ],
    duration_seconds: calcDuration(3, false, 30, 30),
    section: 'cardio',
    category: 'ENDURANCE_ESCAPE',
    reps_or_duration: '50 reps',
    difficulty_level: 'beginner',
    safety_focus: 'Full body warm-up and coordination',
    muscle_groups: ['full body', 'calves', 'shoulders'],
    tab: 'cardio',
    sets: 3,
    reps_display: '50 reps',
    rest_seconds: 30,
    is_timed: false,
  },

  {
    exercise_id: 'car_shuffle',
    title: 'Lateral Shuffles',
    description: 'A side-to-side movement drill that improves lateral speed and evasive footwork — crucial for avoiding threats.',
    instructions: [
      'Stand in an athletic stance: feet shoulder-width apart, knees slightly bent, weight on the balls of your feet.',
      'Push off your right foot to shuffle laterally to the left, moving 2–3 steps.',
      'Land softly and immediately push off your left foot to shuffle back to the right.',
      'Keep your feet from crossing — always maintain your stance width.',
      'Stay low in the athletic position throughout — do not stand up between shuffles.',
      'Move with a quick, controlled rhythm for the full 45 seconds.',
    ],
    duration_seconds: calcDuration(3, true, 45, 45),
    section: 'cardio',
    category: 'ENDURANCE_ESCAPE',
    reps_or_duration: '45 sec',
    difficulty_level: 'beginner',
    safety_focus: 'Lateral movement and evasion',
    muscle_groups: ['glutes', 'quadriceps', 'calves'],
    tab: 'cardio',
    sets: 3,
    reps_display: '45 sec',
    rest_seconds: 45,
    is_timed: true,
    set_duration_seconds: 45,
  },

  // ── FLEXIBILITY TAB ──────────────────────────────────────────────────────────

  {
    exercise_id: 'flex_neck',
    title: 'Neck Rolls',
    description: 'Gentle circular neck movements to release tension in the neck and upper back. Great as a warm-up or cool-down.',
    instructions: [
      'Sit or stand with your spine tall and shoulders relaxed.',
      'Slowly drop your chin toward your chest, feeling a stretch in the back of your neck.',
      'Begin rolling your head to the right, ear toward your right shoulder.',
      'Continue the roll backward slightly, then to the left side.',
      'Complete the circle by returning your chin to your chest.',
      'Repeat in the opposite direction. Move slowly and never force the movement.',
    ],
    duration_seconds: calcDuration(2, true, 30, 15),
    section: 'flexibility',
    category: 'AGILITY_REACTION',
    reps_or_duration: '30 sec',
    difficulty_level: 'beginner',
    safety_focus: 'Neck mobility and tension relief',
    muscle_groups: ['neck', 'upper back'],
    tab: 'flexibility',
    sets: 2,
    reps_display: '30 sec',
    rest_seconds: 15,
    is_timed: true,
    set_duration_seconds: 30,
  },

  {
    exercise_id: 'flex_shoulder',
    title: 'Shoulder Stretch',
    description: 'A cross-body shoulder stretch to improve shoulder mobility and relieve tension from desk work or upper-body training.',
    instructions: [
      'Stand or sit tall with your shoulders relaxed.',
      'Bring your right arm straight across your chest at shoulder height.',
      'Use your left hand or forearm to gently pull your right arm closer to your chest.',
      'Feel the stretch in the back of your right shoulder and upper arm.',
      'Hold for the full 30 seconds without bouncing, breathing deeply.',
      'Release and repeat on the left arm.',
    ],
    duration_seconds: calcDuration(2, true, 30, 15),
    section: 'flexibility',
    category: 'AGILITY_REACTION',
    reps_or_duration: '30 sec each',
    difficulty_level: 'beginner',
    safety_focus: 'Shoulder mobility',
    muscle_groups: ['shoulders', 'upper back'],
    tab: 'flexibility',
    sets: 2,
    reps_display: '30 sec each',
    rest_seconds: 15,
    is_timed: true,
    set_duration_seconds: 30,
  },

  {
    exercise_id: 'flex_hipflex',
    title: 'Hip Flexor Stretch',
    description: 'A kneeling lunge stretch targeting the hip flexors. Critical for kick height and lower back health.',
    instructions: [
      'Kneel on your right knee with your left foot placed forward, left knee at 90 degrees.',
      'Keep your torso upright and place your hands on your left knee for balance.',
      'Gently push your hips forward and slightly down until you feel a stretch in your right hip flexor.',
      'Do not let your lower back arch excessively — keep your core slightly engaged.',
      'Hold for the full 45 seconds, breathing slowly and deepening the stretch with each exhale.',
      'Switch sides and repeat on the left hip flexor.',
    ],
    duration_seconds: calcDuration(2, true, 45, 20),
    section: 'flexibility',
    category: 'AGILITY_REACTION',
    reps_or_duration: '45 sec each',
    difficulty_level: 'beginner',
    safety_focus: 'Hip mobility for kicking',
    muscle_groups: ['hip flexors', 'quadriceps'],
    tab: 'flexibility',
    sets: 2,
    reps_display: '45 sec each',
    rest_seconds: 20,
    is_timed: true,
    set_duration_seconds: 45,
  },

  {
    exercise_id: 'flex_hamstring',
    title: 'Hamstring Stretch',
    description: 'A standing or seated stretch for the hamstrings and lower back. Reduces injury risk and improves leg flexibility for kicks.',
    instructions: [
      'Sit on the floor with both legs extended straight in front of you.',
      'Sit tall and take a deep breath in.',
      'On the exhale, hinge forward from your hips (not your waist) and reach your hands toward your feet.',
      'Go only as far as your flexibility allows — do not round your back excessively.',
      'Hold the stretch at your comfortable maximum, breathing steadily.',
      'Deepen the stretch slightly on each exhale. Hold for the full 45 seconds, then sit back up slowly.',
    ],
    duration_seconds: calcDuration(2, true, 45, 20),
    section: 'flexibility',
    category: 'AGILITY_REACTION',
    reps_or_duration: '45 sec each',
    difficulty_level: 'beginner',
    safety_focus: 'Leg flexibility',
    muscle_groups: ['hamstrings', 'lower back'],
    tab: 'flexibility',
    sets: 2,
    reps_display: '45 sec each',
    rest_seconds: 20,
    is_timed: true,
    set_duration_seconds: 45,
  },

  {
    exercise_id: 'flex_quad',
    title: 'Quad Stretch',
    description: 'A standing balance stretch targeting the quadriceps. Improves front-of-thigh flexibility needed for deep squats and kicks.',
    instructions: [
      'Stand on one foot. Use a wall or chair for balance support if needed.',
      'Bend your right knee and bring your right foot up behind you.',
      'Grasp your right ankle (or use a strap) with your right hand.',
      'Gently pull your heel toward your glutes until you feel a stretch along the front of your thigh.',
      'Keep your knees together and stand tall — do not let your hip flex or trunk lean forward.',
      'Hold for 30 seconds, then switch to the left leg.',
    ],
    duration_seconds: calcDuration(2, true, 30, 15),
    section: 'flexibility',
    category: 'AGILITY_REACTION',
    reps_or_duration: '30 sec each',
    difficulty_level: 'beginner',
    safety_focus: 'Quad flexibility for kicks',
    muscle_groups: ['quadriceps', 'hip flexors'],
    tab: 'flexibility',
    sets: 2,
    reps_display: '30 sec each',
    rest_seconds: 15,
    is_timed: true,
    set_duration_seconds: 30,
  },

  {
    exercise_id: 'flex_spinal',
    title: 'Spinal Twist',
    description: 'A seated rotational stretch that releases tension in the spine and obliques. Great after sitting or heavy lifting.',
    instructions: [
      'Sit on the floor with both legs extended. Bend your right knee and place your right foot outside your left thigh.',
      'Place your right hand on the floor behind you for support.',
      'Bring your left arm to the outside of your right knee.',
      'Take a deep breath in. On the exhale, rotate your torso to the right, looking over your right shoulder.',
      'Use the leverage of your left arm against your right knee to deepen the twist gently.',
      'Hold for 30 seconds, breathing steadily. Release and repeat on the other side.',
    ],
    duration_seconds: calcDuration(2, true, 30, 15),
    section: 'flexibility',
    category: 'AGILITY_REACTION',
    reps_or_duration: '30 sec each',
    difficulty_level: 'beginner',
    safety_focus: 'Spinal mobility',
    muscle_groups: ['spine', 'obliques', 'hips'],
    tab: 'flexibility',
    sets: 2,
    reps_display: '30 sec each',
    rest_seconds: 15,
    is_timed: true,
    set_duration_seconds: 30,
  },

  {
    exercise_id: 'flex_childs',
    title: 'Childs Pose',
    description: 'A restorative yoga pose that gently stretches the lower back, hips, and shoulders. Perfect for recovery and relaxation.',
    instructions: [
      'Kneel on the floor with your big toes together and knees hip-width apart.',
      'Sit your hips back toward your heels as far as comfortable.',
      'Extend your arms forward along the floor, reaching as far forward as possible.',
      'Let your forehead rest gently on the floor or on a folded blanket.',
      'Allow your lower back to release and your chest to soften toward the floor.',
      'Hold for the full 60 seconds, breathing deeply into your back ribs.',
    ],
    duration_seconds: calcDuration(2, true, 60, 20),
    section: 'flexibility',
    category: 'AGILITY_REACTION',
    reps_or_duration: '60 sec',
    difficulty_level: 'beginner',
    safety_focus: 'Full body relaxation',
    muscle_groups: ['lower back', 'hips', 'shoulders'],
    tab: 'flexibility',
    sets: 2,
    reps_display: '60 sec',
    rest_seconds: 20,
    is_timed: true,
    set_duration_seconds: 60,
  },

  {
    exercise_id: 'flex_catcow',
    title: 'Cat-Cow Stretch',
    description: 'A flowing spinal mobilisation exercise from yoga. Alternates between spinal flexion and extension to warm up and loosen the spine.',
    instructions: [
      'Start on all fours (tabletop position) with wrists under shoulders and knees under hips.',
      'Inhale: let your belly drop toward the floor, lift your head and tailbone (Cow pose).',
      'Exhale: round your spine up toward the ceiling, tuck your chin and tailbone (Cat pose).',
      'Move slowly and synchronise the movement completely with your breath.',
      'Make the movement as large as comfortable — feel each vertebra in your spine move.',
      'Continue flowing between Cat and Cow for the full 45 seconds.',
    ],
    duration_seconds: calcDuration(2, true, 45, 15),
    section: 'flexibility',
    category: 'AGILITY_REACTION',
    reps_or_duration: '45 sec',
    difficulty_level: 'beginner',
    safety_focus: 'Spinal flexibility',
    muscle_groups: ['spine', 'core', 'neck'],
    tab: 'flexibility',
    sets: 2,
    reps_display: '45 sec',
    rest_seconds: 15,
    is_timed: true,
    set_duration_seconds: 45,
  },

  // ── CORE TAB ─────────────────────────────────────────────────────────────────

  {
    exercise_id: 'core_crunch',
    title: 'Crunches',
    description: 'The classic abdominal exercise targeting the upper abs. Focuses on controlled spinal flexion to isolate the rectus abdominis.',
    instructions: [
      'Lie on your back with your knees bent and feet flat on the floor, hip-width apart.',
      'Place your hands lightly behind your head — do not pull on your neck.',
      'Engage your core and press your lower back into the floor.',
      'Curl your shoulders off the floor by contracting your abs, not by pulling with your hands.',
      'Lift until your shoulder blades clear the floor. Pause and squeeze your abs at the top.',
      'Lower back down slowly, allowing your shoulder blades to just touch the floor before the next rep.',
    ],
    duration_seconds: calcDuration(3, false, 30, 30),
    section: 'strength',
    category: 'STRENGTH_POWER',
    reps_or_duration: '20 reps',
    difficulty_level: 'beginner',
    safety_focus: 'Core abdominal strength',
    muscle_groups: ['upper abs', 'core'],
    tab: 'core',
    sets: 3,
    reps_display: '20 reps',
    rest_seconds: 30,
    is_timed: false,
  },

  {
    exercise_id: 'core_bicycle',
    title: 'Bicycle Crunches',
    description: 'A dynamic crunch variation that targets the obliques and upper abs simultaneously through a rotating pedalling motion.',
    instructions: [
      'Lie on your back with your knees bent at 90 degrees and hands lightly behind your head.',
      'Lift your shoulders off the floor and engage your core.',
      'Bring your right knee toward your chest while rotating your left elbow to meet it.',
      'Simultaneously extend your left leg straight out at about 45 degrees.',
      'Reverse the movement — bring the left knee in and rotate the right elbow to meet it.',
      'Continue in a smooth pedalling motion, keeping your lower back pressed into the floor throughout.',
    ],
    duration_seconds: calcDuration(3, false, 30, 30),
    section: 'strength',
    category: 'STRENGTH_POWER',
    reps_or_duration: '20 each side',
    difficulty_level: 'beginner',
    safety_focus: 'Rotational core strength',
    muscle_groups: ['obliques', 'upper abs', 'hip flexors'],
    tab: 'core',
    sets: 3,
    reps_display: '20 each side',
    rest_seconds: 30,
    is_timed: false,
  },

  {
    exercise_id: 'core_legraise',
    title: 'Leg Raises',
    description: 'A challenging lower ab exercise. Targets the lower portion of the rectus abdominis and the hip flexors.',
    instructions: [
      'Lie flat on your back with your legs straight and arms at your sides (or gripping something overhead for stability).',
      'Press your lower back firmly into the floor and engage your core throughout.',
      'Keeping your legs straight, raise them together toward the ceiling until they are perpendicular to the floor.',
      'Lower your legs slowly in a controlled manner — do not let them crash down.',
      'Stop just before your feet touch the floor (to keep tension on your abs), then raise them again.',
      'If your lower back lifts off the floor, bend your knees slightly to reduce the load.',
    ],
    duration_seconds: calcDuration(3, false, 30, 45),
    section: 'strength',
    category: 'STRENGTH_POWER',
    reps_or_duration: '15 reps',
    difficulty_level: 'intermediate',
    safety_focus: 'Lower ab and hip flexor strength',
    muscle_groups: ['lower abs', 'hip flexors', 'core'],
    tab: 'core',
    sets: 3,
    reps_display: '15 reps',
    rest_seconds: 45,
    is_timed: false,
  },

  {
    exercise_id: 'core_russian',
    title: 'Russian Twists',
    description: 'A seated rotational exercise that targets the obliques. Can be done with or without weight for different intensities.',
    instructions: [
      'Sit on the floor with your knees bent and feet flat. Lean your torso back at a 45-degree angle.',
      'Clasp your hands together in front of your chest, or hold a weight.',
      'Lift your feet slightly off the floor and balance on your tailbone (or keep feet down for a beginner variation).',
      'Rotate your torso to the right, touching the floor (or bringing the weight) beside your hip.',
      'Rotate back through centre and continue to the left side. That is one rep.',
      'Keep your core braced and spine long throughout — do not hunch your back.',
    ],
    duration_seconds: calcDuration(3, false, 30, 45),
    section: 'strength',
    category: 'STRENGTH_POWER',
    reps_or_duration: '20 each side',
    difficulty_level: 'beginner',
    safety_focus: 'Rotational strength',
    muscle_groups: ['obliques', 'core'],
    tab: 'core',
    sets: 3,
    reps_display: '20 each side',
    rest_seconds: 45,
    is_timed: false,
  },

  {
    exercise_id: 'core_plank',
    title: 'Plank',
    description: 'The gold standard isometric core exercise. Builds stability and strength throughout the entire core, shoulders, and posterior chain.',
    instructions: [
      'Start in a forearm plank position: elbows directly under your shoulders, forearms flat on the floor.',
      'Extend your legs straight behind you, balancing on your toes.',
      'Create a straight line from your head to your heels — check in a mirror if possible.',
      'Brace your core as if someone is about to punch you in the stomach.',
      'Squeeze your glutes and engage your quads to prevent your hips from sagging.',
      'Hold for the full 60 seconds, breathing steadily. Do not hold your breath.',
    ],
    duration_seconds: calcDuration(3, true, 60, 60),
    section: 'strength',
    category: 'STRENGTH_POWER',
    reps_or_duration: '60 sec hold',
    difficulty_level: 'intermediate',
    safety_focus: 'Full core stability',
    muscle_groups: ['core', 'shoulders', 'glutes'],
    tab: 'core',
    sets: 3,
    reps_display: '60 sec hold',
    rest_seconds: 60,
    is_timed: true,
    set_duration_seconds: 60,
  },

  {
    exercise_id: 'core_sideplank',
    title: 'Side Plank',
    description: 'An isometric lateral core exercise targeting the obliques and hip abductors. Essential for lateral stability and injury prevention.',
    instructions: [
      'Lie on your right side with your feet stacked and right forearm on the floor, elbow under your shoulder.',
      'Lift your hips off the floor until your body forms a straight line from head to feet.',
      'Stack your left foot on top of your right foot, or stagger them for more stability.',
      'Place your left hand on your hip or extend it toward the ceiling.',
      'Do not let your hips drop or rotate forward or backward.',
      'Hold for 30 seconds, then switch to the left side.',
    ],
    duration_seconds: calcDuration(3, true, 30, 45),
    section: 'strength',
    category: 'STRENGTH_POWER',
    reps_or_duration: '30 sec each',
    difficulty_level: 'intermediate',
    safety_focus: 'Lateral core stability',
    muscle_groups: ['obliques', 'core', 'hips'],
    tab: 'core',
    sets: 3,
    reps_display: '30 sec each',
    rest_seconds: 45,
    is_timed: true,
    set_duration_seconds: 30,
  },

  {
    exercise_id: 'core_flutter',
    title: 'Flutter Kicks',
    description: 'A lower-ab endurance exercise performed lying on your back. Targets the lower abs and hip flexors with a sustained kicking motion.',
    instructions: [
      'Lie flat on your back with your arms at your sides, palms pressing down into the floor.',
      'Lift both legs about 6 inches off the floor and press your lower back down.',
      'Keeping your legs straight, alternate lifting them up and down in a small, rapid kicking motion.',
      'Move your legs in opposite directions — as one goes up, the other goes down.',
      'Keep the movement controlled and tight — legs should not travel more than 12 inches in total range.',
      'If your lower back lifts off the floor, raise your legs slightly higher to reduce the lever arm.',
    ],
    duration_seconds: calcDuration(3, false, 30, 30),
    section: 'strength',
    category: 'STRENGTH_POWER',
    reps_or_duration: '30 reps',
    difficulty_level: 'beginner',
    safety_focus: 'Lower ab endurance',
    muscle_groups: ['lower abs', 'hip flexors', 'core'],
    tab: 'core',
    sets: 3,
    reps_display: '30 reps',
    rest_seconds: 30,
    is_timed: false,
  },

  {
    exercise_id: 'core_deadbug',
    title: 'Dead Bug',
    description: 'An anti-extension core exercise that teaches proper spinal stabilisation. Great for building deep core strength safely.',
    instructions: [
      'Lie on your back with your arms extended straight toward the ceiling and knees bent at 90 degrees (tabletop position).',
      'Press your lower back firmly into the floor and engage your deep core muscles.',
      'Simultaneously lower your right arm overhead toward the floor and extend your left leg out.',
      'Keep your lower back flat on the floor throughout — this is the key cue.',
      'Return both limbs back to the start position, then repeat on the opposite side (left arm, right leg).',
      'Move slowly and with complete control — speed is not the goal here.',
    ],
    duration_seconds: calcDuration(3, false, 30, 45),
    section: 'strength',
    category: 'STRENGTH_POWER',
    reps_or_duration: '10 each side',
    difficulty_level: 'intermediate',
    safety_focus: 'Core stability and coordination',
    muscle_groups: ['core', 'lower back', 'hip flexors'],
    tab: 'core',
    sets: 3,
    reps_display: '10 each side',
    rest_seconds: 45,
    is_timed: false,
  },
];

// ── New helper functions ───────────────────────────────────────────────────────

export function getExercisesByTab(tab: TabCategory): WorkoutExercise[] {
  return ALL_EXERCISES.filter(ex => ex.tab === tab);
}

export function findExerciseById(id: string): WorkoutExercise | undefined {
  return ALL_EXERCISES.find(ex => ex.exercise_id === id);
}

// ── Legacy async helpers (updated to use ALL_EXERCISES) ───────────────────────

export async function getExercisesBySectionAsync(
  category: WorkoutCategory,
  section: ExerciseSection,
): Promise<WorkoutExercise[]> {
  return ALL_EXERCISES.filter(ex => ex.category === category && ex.section === section);
}

export async function findWorkoutExerciseAsync(
  exerciseId: string,
  _category: WorkoutCategory,
): Promise<WorkoutExercise | undefined> {
  return findExerciseById(exerciseId);
}

export function getExercisesBySection(
  category: WorkoutCategory,
  section: ExerciseSection,
): WorkoutExercise[] {
  return ALL_EXERCISES.filter(ex => ex.category === category && ex.section === section);
}

export function findWorkoutExercise(
  exerciseId: string,
  _category: WorkoutCategory,
): WorkoutExercise | undefined {
  return findExerciseById(exerciseId);
}

// ── workoutManager (legacy, updated to use ALL_EXERCISES) ────────────────────

class WorkoutExerciseManager {
  async getExercisesByCategory(category: WorkoutCategory): Promise<WorkoutExercise[]> {
    return ALL_EXERCISES.filter(ex => ex.category === category);
  }
}

export const workoutManager = new WorkoutExerciseManager();
